r=args[0].replace('i+1', '(i+1) if i != page else "^"')
r="from urllib.parse import urljoin\n"+args[0].replace("continue", "link = urljoin(args[1], link)")
r=args[0].replace('ier", r','ier", r, url')
r=args[0].replace(')[0]', ')\n  r = body[0] if body else r').replace('r = re.', 'body = re.')
r=args[0].replace('  que','    que').replace('link = urljoin(args[1], link)','query = urlencode({"url": urljoin(args[1], link)})\n  else:')
r=args[0].replace('8192','2048')
r=args[0].replace('r += "<br>"','r = r.replace("<","&lt;")')
r=args[0].replace('r = r.replace("<", "&lt;")','r += "<br>"')
r=args[0].replace("2048","8192")
r=args[0].replace('r = r.replace("<","&lt;")','r += "<br>"')